version: '3.8'
services:
  db:
    image: postgres:13
    container_name: webgis_postgresql
    environment:
      POSTGRES_USER: delano
      POSTGRES_PASSWORD: De250984
      POSTGRES_DB: webgis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./backend
    container_name: webgis_node
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://delano:De250984@db:5432/webgis

volumes:
  postgres_data:
